local string_utils = require('bufferize.string_utils')

describe('String utils', function()
    describe('is_not_empty', function()
        it('returns true for non empty string', function()
            assert.True(string_utils.is_not_empty("hello"))
        end)
        it('returns false for empty string', function()
            assert.False(string_utils.is_not_empty(""))
        end)
        it('returns false for nil', function()
            assert.False(string_utils.is_not_empty())
        end)
    end)
end)
